name: EntityControl
main: no.runsafe.entitycontrol.Plugin
version: 1.0.@BUILD@
author: Kruithne
description: Entity control
commands:
  npc:
    description: NPC related commands
  companion:
    description: Companion related commands
  sit:
    description: Sit down!